First iteration
RedrikShuhartRed/finalTODO pull request #1
Opened 2024-07-21 15:40 UTC by RedrikShuhartRed

2024-07-22 14:51 UTC, just-musha commented
@RedrikShuhartRed привет! Склонировала репозиторий, запускаю сервер:
```
go run cmd/main.go 
2024/07/22 17:48:46 main.go:19: error load .env: open .env: no such file or directory
2024/07/22 17:48:46 environment.go:12: TODO_PORT environment variable not found, default is used
2024/07/22 17:48:46 environment.go:15: environment variable is used: port = 7540
2024/07/22 17:48:46 environment.go:22: dbFile environment variable not found, default is used
2024/07/22 17:48:46 environment.go:25: environment variable is used: dbFile = ../cmd/scheduler.db
2024/07/22 17:48:46 db.go:45: Error create table in DB, unable to open database file: out of memory (14)
2024/07/22 17:48:46 main.go:25: Error connect DB, unable to open database file: out of memory (14)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x884855]

goroutine 1 [running]:
main.main()
	/home/mbulatova/projects/yandex-homeworks/sprint-final/finalTODO-RedrikShuhartRed/cmd/main.go:28 +0x1f5
exit status 2

```

Можешь плиз тоже склонить и проверить, что все работает ок? Что сервер запускается, тесты проходят?

2024-07-22 15:09 UTC, RedrikShuhartRed commented
> @RedrikShuhartRed привет! Склонировала репозиторий, запускаю сервер:
> 
> ```
> go run cmd/main.go 
> 2024/07/22 17:48:46 main.go:19: error load .env: open .env: no such file or directory
> 2024/07/22 17:48:46 environment.go:12: TODO_PORT environment variable not found, default is used
> 2024/07/22 17:48:46 environment.go:15: environment variable is used: port = 7540
> 2024/07/22 17:48:46 environment.go:22: dbFile environment variable not found, default is used
> 2024/07/22 17:48:46 environment.go:25: environment variable is used: dbFile = ../cmd/scheduler.db
> 2024/07/22 17:48:46 db.go:45: Error create table in DB, unable to open database file: out of memory (14)
> 2024/07/22 17:48:46 main.go:25: Error connect DB, unable to open database file: out of memory (14)
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x884855]
> 
> goroutine 1 [running]:
> main.main()
> 	/home/mbulatova/projects/yandex-homeworks/sprint-final/finalTODO-RedrikShuhartRed/cmd/main.go:28 +0x1f5
> exit status 2
> ```
> 
> Можешь плиз тоже склонить и проверить, что все работает ок? Что сервер запускается, тесты проходят?

Привет! Надо прям как в README сначала перейти в cmd и оттуда запустить, должно заработать. Через go run cmd/main.go такая же ошибка падает.
![image](https://github.com/user-attachments/assets/6dee8958-9bc6-4fb8-9f3b-40260ebaeb7f)

И тесты тоже все тогда проходят:
![image](https://github.com/user-attachments/assets/2de2812e-8ba4-4aa1-985e-5c2722bc1682)

2024-07-22 15:31 UTC, RedrikShuhartRed commented
> [just-musha](/just-musha)

@just-musha я пока что не нашел решение этой проблемы, так что запуск возможен только непосредственно из папки cmd, из того что пока успел нагуглить, это как то связано именно с самим sqlite

2024-07-22 16:03 UTC, RedrikShuhartRed commented
> > @RedrikShuhartRed привет! Склонировала репозиторий, запускаю сервер:
> > ```
> > go run cmd/main.go 
> > 2024/07/22 17:48:46 main.go:19: error load .env: open .env: no such file or directory
> > 2024/07/22 17:48:46 environment.go:12: TODO_PORT environment variable not found, default is used
> > 2024/07/22 17:48:46 environment.go:15: environment variable is used: port = 7540
> > 2024/07/22 17:48:46 environment.go:22: dbFile environment variable not found, default is used
> > 2024/07/22 17:48:46 environment.go:25: environment variable is used: dbFile = ../cmd/scheduler.db
> > 2024/07/22 17:48:46 db.go:45: Error create table in DB, unable to open database file: out of memory (14)
> > 2024/07/22 17:48:46 main.go:25: Error connect DB, unable to open database file: out of memory (14)
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x884855]
> > 
> > goroutine 1 [running]:
> > main.main()
> > 	/home/mbulatova/projects/yandex-homeworks/sprint-final/finalTODO-RedrikShuhartRed/cmd/main.go:28 +0x1f5
> > exit status 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Можешь плиз тоже склонить и проверить, что все работает ок? Что сервер запускается, тесты проходят?
> 
> Привет! Надо прям как в README сначала перейти в cmd и оттуда запустить, должно заработать. Через go run cmd/main.go такая же ошибка падает. ![image](https://private-user-images.githubusercontent.com/156517536/351016171-6dee8958-9bc6-4fb8-9f3b-40260ebaeb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjM5ODIsIm5iZiI6MTcyMTY2MzY4MiwicGF0aCI6Ii8xNTY1MTc1MzYvMzUxMDE2MTcxLTZkZWU4OTU4LTliYzYtNGZiOC05ZjNiLTQwMjYwZWJhZWI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNTU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGRiMjVmM2UwMjk3N2VlOTRjOWIyZDQyZjM0ZGJiOGYxNzhlYTY5MGZkZTlhOGQ2MDRmNmEzZDNjZWQ3NGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nVpITbU3ji1pwnHTi_7hgDkuJb9KC5eaYaeOFJeJvI4)
> 
> И тесты тоже все тогда проходят: ![image](https://private-user-images.githubusercontent.com/156517536/351016635-2de2812e-8ba4-4aa1-985e-5c2722bc1682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjM5ODIsIm5iZiI6MTcyMTY2MzY4MiwicGF0aCI6Ii8xNTY1MTc1MzYvMzUxMDE2NjM1LTJkZTI4MTJlLThiYTQtNGFhMS05ODVlLTVjMjcyMmJjMTY4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNTU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDA4MWRlNzg4MmM0YzM1ZWE3ZDUzMzgwNDcyNTM5MThiMjU2NTY4NTRhZTY0Y2E3ZjVlMmJiM2UwNjhlMmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rtGjM5NsM2An3yAusn3UvouEBJCuDsRVPTyrJQ9PVtU)



> @RedrikShuhartRed привет! Склонировала репозиторий, запускаю сервер:
> 
> ```
> go run cmd/main.go 
> 2024/07/22 17:48:46 main.go:19: error load .env: open .env: no such file or directory
> 2024/07/22 17:48:46 environment.go:12: TODO_PORT environment variable not found, default is used
> 2024/07/22 17:48:46 environment.go:15: environment variable is used: port = 7540
> 2024/07/22 17:48:46 environment.go:22: dbFile environment variable not found, default is used
> 2024/07/22 17:48:46 environment.go:25: environment variable is used: dbFile = ../cmd/scheduler.db
> 2024/07/22 17:48:46 db.go:45: Error create table in DB, unable to open database file: out of memory (14)
> 2024/07/22 17:48:46 main.go:25: Error connect DB, unable to open database file: out of memory (14)
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x884855]
> 
> goroutine 1 [running]:
> main.main()
> 	/home/mbulatova/projects/yandex-homeworks/sprint-final/finalTODO-RedrikShuhartRed/cmd/main.go:28 +0x1f5
> exit status 2
> ```
> 
> Можешь плиз тоже склонить и проверить, что все работает ок? Что сервер запускается, тесты проходят?

Если вкратце, как я понял, это связано с правами в sqlite, если права у нас не только на чтение, то надо выполнять подключение из той директории, где создается БД. Так как в моем проекте БД создается в cmd, то и команда должна прийти оттуда. Сейчас проверил локально, переписал на создание БД в корневой директории проекта, а не в cmd, и тогда все работает через go run cmd/main.go
```  
$ go run cmd/main.go
2024/07/22 20:03:28 main.go:19: error load .env: open .env: The system cannot find the file specified.
2024/07/22 20:03:28 environment.go:12: TODO_PORT environment variable not found, default is used
2024/07/22 20:03:28 environment.go:15: environment variable is used: port = 7540
2024/07/22 20:03:28 environment.go:22: dbFile environment variable not found, default is used
2024/07/22 20:03:28 environment.go:26: environment variable is used: dbFile = **/finalTODO/scheduler.db**
2024/07/22 20:03:28 db.go:33: /finalTODO/scheduler.db
2024/07/22 20:03:28 db.go:54: Database created successfully.
2024/07/22 20:03:28 main.go:39: Starting server on port 7540...
```

2024-07-22 17:29 UTC, just-musha commented
> Сейчас проверил локально, переписал на создание БД в корневой директории проекта, а не в cmd, и тогда все работает через go run cmd/main.go

О, это хорошо, так будет более очевидно

2024-07-22 17:29 UTC, just-musha commented
@RedrikShuhartRed спасибо, да в cmd ок. Смотрю дальше.

2024-07-23 11:42 UTC, just-musha requested changes
Отписала комментарии по стркутуре кода и по стилю. В целом здоровое что разбито на файлы, и так гораздо легче воспринимается.

2024-07-23 11:42 UTC, just-musha commented on tests/nextdate_3_test.go
> +
Лучше не менять лишние файлы, которые не должны быть изменены. Даже чуть-чуть

2024-07-23 11:42 UTC, just-musha commented on Environment/environment.go
> +package environment
Если ты читаешь ппременные окружения - то это можно сделать прям в main (отдельный пакет не нужен).

Если хочешь конфиг добавить - то тогда уже будет логично  в пакет config вынести.https://dev.to/ilyakaznacheev/a-clean-way-to-pass-configs-in-a-go-application-1g64

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	Dbs *sql.DB
```diff
-Dbs
+db
```

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		log.Printf("ERRRRADARTASFASFJKKFJ")
Этот лог нужен тут?

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	if s.Dbs == nil {
Обычно мы не проверяем в методах что указатель nil,лучше избваиться от этой проверки.

Лучше реализовать так, чтобы Storage с nil внутри не мог быть создан - возаращалась ошибка при создании Storage
Тогда не придется проверять в каждом методе

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	lastId, err := (res.LastInsertId())
Внешние скобки тут точно нужны? Мб их убрать?

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		log.Printf("error insert into scheduler, %v", err)
Лучше логировать не на уровне db, а где-то выше уровнем - где больше информации о том, какой запрос и так далее. На db ур лучше оборачивать ошибку. (но в данной работе это не обязательно)

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	limit := 20
Числа лучше вынести из метода, в константы с понятными названиями

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	timeFormat := "02.01.2006"
И это тоже выглядит как некая константа

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	if err != nil {
После цикла ещё не забыть проверить rows.Err

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		log.Printf("error getting rows affected: %v", err)
return потерялся?

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		log.Printf("no rows affected: %v", err)
return не потерялся?

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		log.Printf("error checking rows affected: %v", err)
return

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		log.Printf("task not found for id: %v", id)
return

2024-07-23 11:42 UTC, just-musha commented on models/models.go
> +func (task *Task) CheckDate() (string, error) {
Этот метод должен лежать где-то поближе к месту где он используется. Не в models, а поближе к хендлерам, видимо

2024-07-23 11:42 UTC, just-musha commented on models/models.go
> +func (task *Task) CheckDoneDate() (string, error) {
И этот тоже

2024-07-23 11:42 UTC, just-musha commented on models/models.go
> +func (task *Task) CheckDate() (string, error) {
тогда можно не делать методами, и передавать туда task как параметр (не критично для работы)

2024-07-23 11:42 UTC, just-musha commented on api/middleware/jsonErrors.go
> +	json.NewEncoder(w).Encode(resp)
Тут нужно проверить и вернуть ошибку

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	_ "modernc.org/sqlite"
Сортировка импортов - нужно разбить по блокам. Стандартные пакеты, потом внешние, потом внутренние если есть.

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +	_ "modernc.org/sqlite"
Это нужно пройтись по каждому файлу и поправить

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		if errors.Is(err, sql.ErrNoRows) {
А для чего выделяешь это в отдельный случай? Можно этого не делать? Будет проще, а чем проще - тем лучше

2024-07-23 11:42 UTC, just-musha commented on api/handlers/utils.go
> +func CheckId(id string) error {
Лучше не заводить файл utils ( как и пакет, ксатти). В Го это плохая практика. Лучше положить этот метод поблже к месту где он используется

2024-07-23 11:42 UTC, just-musha commented on db/db.go
> +		searchdate, err := time.Parse(timeFormat, search)
Тут можешь подумать как убрать часть логики на уровень выше. По идее в db - обертка над операциями к БД, Условно 1 метод - 1 запрос. Тут уже более сложная штука, вызывает 2 метода, и можно её вынесите повыше, и чтоб она внутри дергала более просты методы.

Но это оставлю на твое усмотрение

2024-07-23 20:20 UTC, RedrikShuhartRed commented on tests/nextdate_3_test.go
> +
Вернул на место

2024-07-23 20:20 UTC, RedrikShuhartRed commented on Environment/environment.go
> +package environment
Создал пакет config

2024-07-23 20:20 UTC, RedrikShuhartRed commented on db/db.go
> +	Dbs *sql.DB
Исправлено

2024-07-23 20:21 UTC, RedrikShuhartRed commented on db/db.go
> +		log.Printf("ERRRRADARTASFASFJKKFJ")
Остался после какой-то фигни с ДБ, когда она в nil уходила, убрал

2024-07-23 20:21 UTC, RedrikShuhartRed commented on db/db.go
> +	if s.Dbs == nil {
Убрано

2024-07-23 20:21 UTC, RedrikShuhartRed commented on api/middleware/jsonErrors.go
> +	json.NewEncoder(w).Encode(resp)
Сделано

2024-07-23 20:22 UTC, RedrikShuhartRed commented on db/db.go
> +	_ "modernc.org/sqlite"
Сделано

2024-07-23 20:22 UTC, RedrikShuhartRed commented on db/db.go
> +		if errors.Is(err, sql.ErrNoRows) {
Да, здесь не нужно, убрал

2024-07-23 20:24 UTC, RedrikShuhartRed commented on api/handlers/utils.go
> +func CheckId(id string) error {
Создал новый пакет в api, checkQueryParam, туда убрал все обработки. Просто читал где-то, что middleware для обработки чего связанного с "клиент-сервер", а все остальное, типа обработки каких-то данных в utils, видимо не то читал

2024-07-23 20:26 UTC, RedrikShuhartRed commented on db/db.go
> +		searchdate, err := time.Parse(timeFormat, search)
Сделал отдельную функцию для проверки параметра search и три отдельных метода в бд, для каждого случая, в хендлере функция возвращает один из методов

2024-07-23 20:27 UTC, RedrikShuhartRed commented on tests/nextdate_3_test.go
> +
и запуск теперь через go run cmd/main.go работает из корневой директории

2024-07-23 20:31 UTC, RedrikShuhartRed commented on db/db.go
> +		log.Printf("error insert into scheduler, %v", err)
не убрал, но я правильно понимаю, что если я логирую это при вызове хендлере, то из БД это надо убирать?

2024-07-23 20:32 UTC, RedrikShuhartRed commented on db/db.go
> +	if err != nil {
проверено

2024-07-23 20:32 UTC, RedrikShuhartRed commented on db/db.go
> +		log.Printf("error getting rows affected: %v", err)
появился

2024-07-23 20:32 UTC, RedrikShuhartRed commented on db/db.go
> +		log.Printf("no rows affected: %v", err)
появился

2024-07-23 20:32 UTC, RedrikShuhartRed commented on db/db.go
> +		log.Printf("error checking rows affected: %v", err)
появился

2024-07-23 20:32 UTC, RedrikShuhartRed commented on db/db.go
> +		log.Printf("task not found for id: %v", id)
появился

2024-07-24 07:56 UTC, just-musha commented on db/db.go
> +		log.Printf("error insert into scheduler, %v", err)
> не убрал, но я правильно понимаю, что если я логирую это при вызове хендлере, то из БД это надо убирать?

Да, лучше логировать 1 ошибку 1 раз

2024-07-24 09:16 UTC, just-musha requested changes
Последние штрихи

2024-07-24 09:16 UTC, just-musha commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil && (len(task.Date) == 0) || task.Date == "today" {
Можно ли как-то упростить эту функцию? Очень много условай в else if
Предлагаю подумать как можно "распутать" эту логику и сделать функцию более понятной

Как вариант -  можно сделать более линейно - проверка - какие-то действия и returm. И дале следующая проверка
```
if err != nil {
    ....
    return 
}

if time ... {
    ....
    return
}
.....
```

2024-07-24 09:16 UTC, just-musha commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil && (len(task.Date) == 0) || task.Date == "today" {
И тут предлагаю подумать как упростить

2024-07-24 09:16 UTC, just-musha commented on api/routes.go
> +	"github.com/RedrikShuhartRed/finalTODO/config"
Сортировка импортов (внешние в отдельный блок и выше)

2024-07-24 09:16 UTC, just-musha commented on cmd/main.go
> +	cfg, err := config.NewConfig()
:+1: топ

2024-07-24 09:16 UTC, just-musha commented on config/config.go
> +		return nil, errors.New("TODO_PASSWORD environment variable required but not set")
Как насчет дефолные значения  задать? По идее переменные окружение больше для переопределения каких-то дефолтных значиний, по желанию юзера

2024-07-24 09:16 UTC, just-musha commented on api/handlers/tasks.go
> +func AddNewTask(w http.ResponseWriter, r *http.Request, storage *db.Storage) {
Чтоб не передаватаь параметром storage - ты моежшь сделать структуру Handler и положить db в нее. И хендлеры сделать методами этой стркутуры

2024-07-24 18:25 UTC, RedrikShuhartRed commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil && (len(task.Date) == 0) || task.Date == "today" {
Упростил

2024-07-24 18:25 UTC, RedrikShuhartRed commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil && (len(task.Date) == 0) || task.Date == "today" {
Упростил

2024-07-24 18:26 UTC, RedrikShuhartRed commented on api/routes.go
> +	"github.com/RedrikShuhartRed/finalTODO/config"
Сделано

2024-07-24 18:26 UTC, RedrikShuhartRed commented on config/config.go
> +		return nil, errors.New("TODO_PASSWORD environment variable required but not set")
Заданы дефолтные значения, в .env значения пустые

2024-07-24 18:27 UTC, RedrikShuhartRed commented on api/handlers/tasks.go
> +func AddNewTask(w http.ResponseWriter, r *http.Request, storage *db.Storage) {
Создал структуру, добавил так же в свойства config, чтобы его тоже не передавать в хендлеры авторизации и в routes

2024-07-24 19:14 UTC, just-musha requested changes
Почти! Главное - проверка rows.Err, без него не могу принять. Это было в курсе потому что! (см 8 спринт. Остальное - на твое усмотрение

2024-07-24 19:14 UTC, just-musha commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil {
Я бы этот кейс вынесла наверх (когда читаешь код  - ожидаешь после err увидеть сразу что будет в случае ошибки)

2024-07-24 19:14 UTC, just-musha commented on api/checkQueryParam/checkQueryParam.go
> +	task.Date, err = task_transfer.NextDate(now, task.Date, task.Repeat)
Тут могу ошибаться, но - этот код достижим? как будто выше 2 возможных кейса `err == nil `и `err != nil`, и третьего не дано.

2024-07-24 19:14 UTC, just-musha commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil {
Тут аналогично - вынесла бы это наверх, чтобы не шокировать читателей кода, привыкших видеть паттерн
```
err := ...
if err != nil {
    ....
}
```

2024-07-24 19:14 UTC, just-musha commented on api/checkQueryParam/checkQueryParam.go
> +	task.Date, err = task_transfer.NextDate(now, task.Date, task.Repeat)
И снова вопрос достижимости кода (могу ошибаться, повторюсь)

2024-07-24 19:14 UTC, just-musha commented on api/handlers/auth.go
> +func (h *Handler) AuthorizationGetToken(w http.ResponseWriter, r *http.Request) {
:+1: да!

2024-07-24 19:14 UTC, just-musha commented on api/handlers/tasks.go
> +	cfg     *config.Config
Отличное решение затащись сюда конфиг :+1:

2024-07-24 19:14 UTC, just-musha commented on api/routes.go
> +	handler := handlers.NewHandler(storage, cfg)
Красивое теперь

2024-07-24 19:14 UTC, just-musha commented on config/config.go
> +		port = "7540"
Предложила бы вынести наверх и в константы с названием типа defaultPort 
Чтоб все в одном месте лежали

2024-07-24 19:14 UTC, just-musha commented on task_transfer/task_transfer.go
> +	PenultimatetDayInMounthArgument = -2
Тоже хорошее решение

2024-07-24 19:14 UTC, just-musha commented on api/handlers/auth.go
> +	res, _ := json.Marshal(&map[string]string{"token": signedToken})
Пропустила момент с обработкой ошибки - нужно явно обработать тут её

2024-07-24 19:14 UTC, just-musha commented on db/db.go
> +	if err != nil {
Эту ошибку лучше проверить в цикле сразу после Scan

2024-07-24 19:14 UTC, just-musha commented on db/db.go
> +	err = rows.Err()
А вот эту - сразу после цикла

2024-07-24 19:16 UTC, just-musha commented
@RedrikShuhartRed давай ещё чуть-чуть :100:

2024-07-24 20:13 UTC, RedrikShuhartRed commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil {
Вынесено наверх

2024-07-24 20:14 UTC, RedrikShuhartRed commented on api/checkQueryParam/checkQueryParam.go
> +	task.Date, err = task_transfer.NextDate(now, task.Date, task.Repeat)
Тут действительно он не нужен, убрал

2024-07-24 20:14 UTC, RedrikShuhartRed commented on api/checkQueryParam/checkQueryParam.go
> +	if err != nil {
Вынесено наверх

2024-07-24 20:14 UTC, RedrikShuhartRed commented on api/checkQueryParam/checkQueryParam.go
> +	task.Date, err = task_transfer.NextDate(now, task.Date, task.Repeat)
Вот тут все таки нужен, оставлен

2024-07-24 20:15 UTC, RedrikShuhartRed commented on config/config.go
> +		port = "7540"
Созданы default константы

2024-07-24 20:15 UTC, RedrikShuhartRed commented on api/handlers/auth.go
> +	res, _ := json.Marshal(&map[string]string{"token": signedToken})
добавил обработку ошибки

2024-07-24 20:16 UTC, RedrikShuhartRed commented on db/db.go
> +	if err != nil {
Исправлена обработка ошибок во всех случаях использования rows.Next()

2024-07-24 20:16 UTC, RedrikShuhartRed commented on db/db.go
> +	err = rows.Err()
Исправлена обработка ошибок во всех случаях использования rows.Next()

2024-07-24 21:19 UTC, just-musha approved these changes
Поздравляю! Финальный проект принят.

Проделана большая работа, круто что сделал доп. задания, а не только основные. А также что внимательно относился к правкам, даже тем которые были как рекомендации. Надеюсь получилось полезно. 
Пусть изучение на этом не останавливается! Удачи!

2024-07-25 14:49 UTC, RedrikShuhartRed commented
> Поздравляю! Финальный проект принят.
> 
> Проделана большая работа, круто что сделал доп. задания, а не только основные. А также что внимательно относился к правкам, даже тем которые были как рекомендации. Надеюсь получилось полезно. Пусть изучение на этом не останавливается! Удачи!

Большое спасибо! Это супер крутое ревью, лучшее за весь курс, проект из начального "уродца", превратился в что-то адекватное) Успеха во всех начинаниях и только хорошего кода на ревью, а не как мой)

2024-07-27 08:38 UTC, merged